LightningDev/force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <description>To Save Patient Data</description>
    <label>Patient</label>
    <nameField>
        <displayFormat>AH-{000}-{MMYYYY}</displayFormat>
        <label>Patient Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LightningDev/force-app/main/default/objects/Patient__c/fields/Patient_First_name__c.field-meta.xml
<CustomField>
    <fullName>Patient_First_name__c</fullName>
    <description>This is Patient first name</description>
    <inlineHelpText>Do not enter short form</inlineHelpText>
    <label>Patient First name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LightningDev/force-app/main/default/objects/Patient__c/fields/Patient_Primary_email__c.field-meta.xml
<CustomField>
    <fullName>Patient_Primary_email__c</fullName>
    <defaultValue>&apos;no@gmail.com&apos;</defaultValue>
    <externalId>true</externalId>
    <label>Patient Primary email</label>
    <type>Email</type>
</CustomField>

LightningDev/force-app/main/default/classes/batchapex_contact_to_patient.cls
public class batchapex_contact_to_patient implements database.Batchable<sobject>
{
   public list<contact> start(database.BatchableContext cp)
   {
       list<contact> conlst=[select LastName,Email from contact];
       return conlst;
   }
    public void execute(database.BatchableContext cp, list<contact> con)
    {
      for(contact EC:CON)
      {
          Patient__c P= new Patient__c();
         P.Patient_First_name__c=EC.LastName;
          P.Patient_Primary_email__c=EC.email;
          database.insert(P,false);
      }
    }
public void finish(database.BatchableContext cp)
{
    
}
}